import { describe, expect, it, vi } from 'vitest'

import { baseBlobSeeds, blobAreaTargets, blobTreemap, categoryTheme, orientationAcceleration, roundedPath, seedParticles, smoothBlobPolygon, stepSeedPhysics, subscribeDeviceOrientation } from './expense-bubbles'

const items = [
  { id: 'food', label: '食費', amount: 17_600, icon: 'category-food', color: '#000' }, { id: 'daily', label: '日用品', amount: 10_470, icon: 'category-daily', color: '#000' },
  { id: 'transit', label: '交通費', amount: 11_870, icon: 'category-transit', color: '#000' }, { id: 'utility', label: '光熱費', amount: 6_320, icon: 'category-utility', color: '#000' },
  { id: 'subscription', label: 'サブスク', amount: 7_560, icon: 'category-subscription', color: '#000' }, { id: 'other', label: 'その他', amount: 10_780, icon: 'category-other', color: '#000' },
]

describe('blob treemap', () => {
  it('uses deterministic all-curved SVG paths rather than circle divs', () => { const first = blobTreemap(items, 370, 228); expect(blobTreemap(items, 370, 228).map((cell) => cell.path)).toEqual(first.map((cell) => cell.path)); expect(first.every((cell) => cell.path.startsWith('M ') && cell.path.includes(' C '))).toBe(true); expect(roundedPath([{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 5, y: 8 }])).toContain(' C ') })
  it('keeps six zero-yen categories readable and gives one populated category a bounded organic cell', () => { const total = 370 * 228; const zeroes = items.map((item) => ({ ...item, amount: 0 })); const allZeroTargets = blobAreaTargets(zeroes, 370, 228); expect(new Set(allZeroTargets.map((area) => area.toFixed(3))).size).toBe(1); expect(allZeroTargets[0]! / total).toBeCloseTo(1 / 6); const single = items.map((item) => ({ ...item, amount: item.id === 'other' ? 1_234 : 0 })); const targets = blobAreaTargets(single, 370, 228); expect(Math.max(...targets) / total).toBeLessThanOrEqual(0.46); expect(Math.min(...targets) / total).toBeGreaterThanOrEqual(0.1); const layout = blobTreemap(single, 370, 228); const other = layout.find((cell) => cell.id === 'other')!; const zeroCells = layout.filter((cell) => cell.id !== 'other'); expect(other.area).toBeGreaterThan(Math.max(...zeroCells.map((cell) => cell.area))); zeroCells.forEach((cell) => { const xs = cell.inner.map((point) => point.x); const ys = cell.inner.map((point) => point.y); expect(Math.max(...xs) - Math.min(...xs)).toBeGreaterThan(58); expect(Math.abs(cell.centroid.x - (Math.min(...xs) + Math.max(...xs)) / 2) + Math.abs(cell.centroid.y - (Math.min(...ys) + Math.max(...ys)) / 2)).toBeGreaterThan(0.8) }); const foodOnly = blobTreemap(items.map((item) => ({ ...item, amount: item.id === 'food' ? 1_234 : 0 })), 370, 228); expect(foodOnly.find((cell) => cell.id === 'food')!.area).toBeGreaterThan(foodOnly.find((cell) => cell.id === 'other')!.area) })
  it('redistributes a two-category skew without making the smaller cells slivers', () => { const total = 370 * 228; const skewed = items.map((item) => ({ ...item, amount: item.id === 'food' ? 9_000 : item.id === 'daily' ? 1_000 : 0 })); const targets = blobAreaTargets(skewed, 370, 228); const layout = blobTreemap(skewed, 370, 228); expect(Math.max(...targets) / total).toBeLessThanOrEqual(0.4); expect(Math.min(...targets) / total).toBeGreaterThan(0.09); expect(Math.max(...layout.map((cell) => cell.area)) / total).toBeLessThan(0.46); expect(Math.min(...layout.map((cell) => cell.area)) / total).toBeGreaterThan(0.08) })
  it('keeps six different money values nondegenerate while retaining their Figma reference rhythm', () => { const layout = blobTreemap(items, 370, 228); const targets = blobAreaTargets(items, 370, 228); expect(layout.reduce((sum, cell) => sum + cell.area, 0)).toBeCloseTo(370 * 228, -1); layout.forEach((cell, index) => expect(cell.area / targets[index]!).toBeGreaterThan(0.76)); expect(layout.find((cell) => cell.id === 'food')!.area).toBeGreaterThan(layout.find((cell) => cell.id === 'utility')!.area); expect(layout.every((cell) => cell.area > 0)).toBe(true) })
  it('keeps a thin gap and does not change target areas for gyro seed movement', () => { const layout = blobTreemap(items, 370, 228); expect(layout.reduce((sum, cell) => sum + cell.inner.length, 0)).toBeGreaterThan(18); const targets = blobAreaTargets(items, 370, 228); const shifted = baseBlobSeeds(370, 228).map((seed) => ({ x: seed.x + 2, y: seed.y - 1 })); expect(blobAreaTargets(items, 370, 228)).toEqual(targets); expect(blobTreemap(items, 370, 228, shifted)).toHaveLength(6) })
  it('smooths and area-corrects the original straight polygon', () => { const polygon = [{ x: 0, y: 0 }, { x: 100, y: 0 }, { x: 100, y: 80 }, { x: 0, y: 80 }]; const smooth = smoothBlobPolygon(polygon); expect(smooth).toHaveLength(16); const area = (points: typeof polygon) => Math.abs(points.reduce((sum, point, index) => { const next = points[(index + 1) % points.length]!; return sum + point.x * next.y - next.x * point.y }, 0) / 2); expect(area(smooth)).toBeCloseTo(area(polygon), 5) })
  it('keeps inertia after drag release and uses gyro acceleration with damping', () => { const particles = seedParticles(370, 228); const particle = particles[0]!; particle.vx = 8; const start = particle.x; stepSeedPhysics(particles, 370, 228, { x: 0, y: 0 }, 1); expect(particle.x).toBeGreaterThan(start); expect(particle.vx).toBeLessThan(8); const still = particles.map((seed) => ({ ...seed })); stepSeedPhysics(still, 370, 228, { x: 0, y: 0 }, 1); stepSeedPhysics(particles, 370, 228, { x: 0.08, y: 0 }, 1); expect(particle.vx).toBeGreaterThan(still[0]!.vx) })
  it('cleans up an orientation subscription', () => { const added = vi.fn(); const removed = vi.fn(); const stop = subscribeDeviceOrientation({ addEventListener: added, removeEventListener: removed } as unknown as Pick<Window, 'addEventListener' | 'removeEventListener'>, () => undefined); stop(); expect(added).toHaveBeenCalledWith('deviceorientation', expect.any(Function)); expect(removed).toHaveBeenCalledWith('deviceorientation', expect.any(Function)) })
  it('uses Figma foreground colours for pale categories and a safe orientation fallback', () => { expect(categoryTheme(items[0]!)).toEqual({ background: '#708779', foreground: '#ffffff' }); expect(categoryTheme(items[2]!)).toEqual({ background: '#c4cfdb', foreground: '#34465a' }); expect(categoryTheme(items[3]!)).toEqual({ background: '#d0cbd9', foreground: '#4d4862' }); expect(categoryTheme(items[4]!)).toEqual({ background: '#e5cbcd', foreground: '#70474b' }); expect(categoryTheme(items[5]!)).toEqual({ background: '#d1d1cf', foreground: '#171717' }); expect(orientationAcceleration(null, undefined)).toEqual({ x: 0, y: 0 }) })
})
