/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiAssetsHistoryRouteImport } from './routes/api/assets/history'
import { Route as ApiAssetsTransfersRouteImport } from './routes/api/assets/transfers'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiLedgerAnalyticsRouteImport } from './routes/api/ledger/analytics'
import { Route as ApiLedgerSummaryRouteImport } from './routes/api/ledger/summary'
import { Route as ApiOcrReceiptRouteImport } from './routes/api/ocr/receipt'
import { Route as ApiReceiptsIdRouteImport } from './routes/api/receipts/$id'
import { Route as ApiAssetsAccountsIndexRouteImport } from './routes/api/assets/accounts/index'
import { Route as ApiAssetsAccountsIdRouteImport } from './routes/api/assets/accounts/$id'
import { Route as ApiLedgerCategoriesIndexRouteImport } from './routes/api/ledger/categories/index'
import { Route as ApiLedgerCategoriesIdRouteImport } from './routes/api/ledger/categories/$id'
import { Route as ApiLedgerTransactionsIndexRouteImport } from './routes/api/ledger/transactions/index'
import { Route as ApiLedgerTransactionsIdRouteImport } from './routes/api/ledger/transactions/$id'
import { Route as ApiLedgerTransactionsDuplicatesRouteImport } from './routes/api/ledger/transactions/duplicates'
import { Route as ApiPlanningMonthlyTargetsIndexRouteImport } from './routes/api/planning/monthly-targets/index'
import { Route as ApiPlanningMonthlyTargetsIdRouteImport } from './routes/api/planning/monthly-targets/$id'
import { Route as ApiPlanningRecurringRulesIndexRouteImport } from './routes/api/planning/recurring-rules/index'
import { Route as ApiPlanningRecurringRulesIdRouteImport } from './routes/api/planning/recurring-rules/$id'
import { Route as ApiPlanningRecurringRulesRunRouteImport } from './routes/api/planning/recurring-rules/run'
import { Route as ApiReceiptsIdImageRouteImport } from './routes/api/receipts/$id/image'
import { Route as ApiReceiptsIdRetryRouteImport } from './routes/api/receipts/$id/retry'
import { Route as ApiAssetsAccountsIdAdjustmentsRouteImport } from './routes/api/assets/accounts/$id/adjustments'
import { Route as ApiAssetsAccountsIdEntriesRouteImport } from './routes/api/assets/accounts/$id/entries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsHistoryRoute = ApiAssetsHistoryRouteImport.update({
  id: '/api/assets/history',
  path: '/api/assets/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsTransfersRoute = ApiAssetsTransfersRouteImport.update({
  id: '/api/assets/transfers',
  path: '/api/assets/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerAnalyticsRoute = ApiLedgerAnalyticsRouteImport.update({
  id: '/api/ledger/analytics',
  path: '/api/ledger/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerSummaryRoute = ApiLedgerSummaryRouteImport.update({
  id: '/api/ledger/summary',
  path: '/api/ledger/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOcrReceiptRoute = ApiOcrReceiptRouteImport.update({
  id: '/api/ocr/receipt',
  path: '/api/ocr/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptsIdRoute = ApiReceiptsIdRouteImport.update({
  id: '/api/receipts/$id',
  path: '/api/receipts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsAccountsIndexRoute = ApiAssetsAccountsIndexRouteImport.update({
  id: '/api/assets/accounts/',
  path: '/api/assets/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsAccountsIdRoute = ApiAssetsAccountsIdRouteImport.update({
  id: '/api/assets/accounts/$id',
  path: '/api/assets/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerCategoriesIndexRoute =
  ApiLedgerCategoriesIndexRouteImport.update({
    id: '/api/ledger/categories/',
    path: '/api/ledger/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLedgerCategoriesIdRoute = ApiLedgerCategoriesIdRouteImport.update({
  id: '/api/ledger/categories/$id',
  path: '/api/ledger/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerTransactionsIndexRoute =
  ApiLedgerTransactionsIndexRouteImport.update({
    id: '/api/ledger/transactions/',
    path: '/api/ledger/transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLedgerTransactionsIdRoute = ApiLedgerTransactionsIdRouteImport.update({
  id: '/api/ledger/transactions/$id',
  path: '/api/ledger/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerTransactionsDuplicatesRoute =
  ApiLedgerTransactionsDuplicatesRouteImport.update({
    id: '/api/ledger/transactions/duplicates',
    path: '/api/ledger/transactions/duplicates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlanningMonthlyTargetsIndexRoute =
  ApiPlanningMonthlyTargetsIndexRouteImport.update({
    id: '/api/planning/monthly-targets/',
    path: '/api/planning/monthly-targets/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlanningMonthlyTargetsIdRoute =
  ApiPlanningMonthlyTargetsIdRouteImport.update({
    id: '/api/planning/monthly-targets/$id',
    path: '/api/planning/monthly-targets/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlanningRecurringRulesIndexRoute =
  ApiPlanningRecurringRulesIndexRouteImport.update({
    id: '/api/planning/recurring-rules/',
    path: '/api/planning/recurring-rules/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlanningRecurringRulesIdRoute =
  ApiPlanningRecurringRulesIdRouteImport.update({
    id: '/api/planning/recurring-rules/$id',
    path: '/api/planning/recurring-rules/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlanningRecurringRulesRunRoute =
  ApiPlanningRecurringRulesRunRouteImport.update({
    id: '/api/planning/recurring-rules/run',
    path: '/api/planning/recurring-rules/run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReceiptsIdImageRoute = ApiReceiptsIdImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiReceiptsIdRoute,
} as any)
const ApiReceiptsIdRetryRoute = ApiReceiptsIdRetryRouteImport.update({
  id: '/retry',
  path: '/retry',
  getParentRoute: () => ApiReceiptsIdRoute,
} as any)
const ApiAssetsAccountsIdAdjustmentsRoute =
  ApiAssetsAccountsIdAdjustmentsRouteImport.update({
    id: '/adjustments',
    path: '/adjustments',
    getParentRoute: () => ApiAssetsAccountsIdRoute,
  } as any)
const ApiAssetsAccountsIdEntriesRoute =
  ApiAssetsAccountsIdEntriesRouteImport.update({
    id: '/entries',
    path: '/entries',
    getParentRoute: () => ApiAssetsAccountsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/assets/history': typeof ApiAssetsHistoryRoute
  '/api/assets/transfers': typeof ApiAssetsTransfersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ledger/analytics': typeof ApiLedgerAnalyticsRoute
  '/api/ledger/summary': typeof ApiLedgerSummaryRoute
  '/api/ocr/receipt': typeof ApiOcrReceiptRoute
  '/api/receipts/$id': typeof ApiReceiptsIdRouteWithChildren
  '/api/assets/accounts/$id': typeof ApiAssetsAccountsIdRouteWithChildren
  '/api/ledger/categories/$id': typeof ApiLedgerCategoriesIdRoute
  '/api/ledger/transactions/$id': typeof ApiLedgerTransactionsIdRoute
  '/api/ledger/transactions/duplicates': typeof ApiLedgerTransactionsDuplicatesRoute
  '/api/planning/monthly-targets/$id': typeof ApiPlanningMonthlyTargetsIdRoute
  '/api/planning/recurring-rules/$id': typeof ApiPlanningRecurringRulesIdRoute
  '/api/planning/recurring-rules/run': typeof ApiPlanningRecurringRulesRunRoute
  '/api/receipts/$id/image': typeof ApiReceiptsIdImageRoute
  '/api/receipts/$id/retry': typeof ApiReceiptsIdRetryRoute
  '/api/assets/accounts/': typeof ApiAssetsAccountsIndexRoute
  '/api/ledger/categories/': typeof ApiLedgerCategoriesIndexRoute
  '/api/ledger/transactions/': typeof ApiLedgerTransactionsIndexRoute
  '/api/planning/monthly-targets/': typeof ApiPlanningMonthlyTargetsIndexRoute
  '/api/planning/recurring-rules/': typeof ApiPlanningRecurringRulesIndexRoute
  '/api/assets/accounts/$id/adjustments': typeof ApiAssetsAccountsIdAdjustmentsRoute
  '/api/assets/accounts/$id/entries': typeof ApiAssetsAccountsIdEntriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/assets/history': typeof ApiAssetsHistoryRoute
  '/api/assets/transfers': typeof ApiAssetsTransfersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ledger/analytics': typeof ApiLedgerAnalyticsRoute
  '/api/ledger/summary': typeof ApiLedgerSummaryRoute
  '/api/ocr/receipt': typeof ApiOcrReceiptRoute
  '/api/receipts/$id': typeof ApiReceiptsIdRouteWithChildren
  '/api/assets/accounts/$id': typeof ApiAssetsAccountsIdRouteWithChildren
  '/api/ledger/categories/$id': typeof ApiLedgerCategoriesIdRoute
  '/api/ledger/transactions/$id': typeof ApiLedgerTransactionsIdRoute
  '/api/ledger/transactions/duplicates': typeof ApiLedgerTransactionsDuplicatesRoute
  '/api/planning/monthly-targets/$id': typeof ApiPlanningMonthlyTargetsIdRoute
  '/api/planning/recurring-rules/$id': typeof ApiPlanningRecurringRulesIdRoute
  '/api/planning/recurring-rules/run': typeof ApiPlanningRecurringRulesRunRoute
  '/api/receipts/$id/image': typeof ApiReceiptsIdImageRoute
  '/api/receipts/$id/retry': typeof ApiReceiptsIdRetryRoute
  '/api/assets/accounts': typeof ApiAssetsAccountsIndexRoute
  '/api/ledger/categories': typeof ApiLedgerCategoriesIndexRoute
  '/api/ledger/transactions': typeof ApiLedgerTransactionsIndexRoute
  '/api/planning/monthly-targets': typeof ApiPlanningMonthlyTargetsIndexRoute
  '/api/planning/recurring-rules': typeof ApiPlanningRecurringRulesIndexRoute
  '/api/assets/accounts/$id/adjustments': typeof ApiAssetsAccountsIdAdjustmentsRoute
  '/api/assets/accounts/$id/entries': typeof ApiAssetsAccountsIdEntriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/assets/history': typeof ApiAssetsHistoryRoute
  '/api/assets/transfers': typeof ApiAssetsTransfersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ledger/analytics': typeof ApiLedgerAnalyticsRoute
  '/api/ledger/summary': typeof ApiLedgerSummaryRoute
  '/api/ocr/receipt': typeof ApiOcrReceiptRoute
  '/api/receipts/$id': typeof ApiReceiptsIdRouteWithChildren
  '/api/assets/accounts/$id': typeof ApiAssetsAccountsIdRouteWithChildren
  '/api/ledger/categories/$id': typeof ApiLedgerCategoriesIdRoute
  '/api/ledger/transactions/$id': typeof ApiLedgerTransactionsIdRoute
  '/api/ledger/transactions/duplicates': typeof ApiLedgerTransactionsDuplicatesRoute
  '/api/planning/monthly-targets/$id': typeof ApiPlanningMonthlyTargetsIdRoute
  '/api/planning/recurring-rules/$id': typeof ApiPlanningRecurringRulesIdRoute
  '/api/planning/recurring-rules/run': typeof ApiPlanningRecurringRulesRunRoute
  '/api/receipts/$id/image': typeof ApiReceiptsIdImageRoute
  '/api/receipts/$id/retry': typeof ApiReceiptsIdRetryRoute
  '/api/assets/accounts/': typeof ApiAssetsAccountsIndexRoute
  '/api/ledger/categories/': typeof ApiLedgerCategoriesIndexRoute
  '/api/ledger/transactions/': typeof ApiLedgerTransactionsIndexRoute
  '/api/planning/monthly-targets/': typeof ApiPlanningMonthlyTargetsIndexRoute
  '/api/planning/recurring-rules/': typeof ApiPlanningRecurringRulesIndexRoute
  '/api/assets/accounts/$id/adjustments': typeof ApiAssetsAccountsIdAdjustmentsRoute
  '/api/assets/accounts/$id/entries': typeof ApiAssetsAccountsIdEntriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/signup'
    | '/api/health'
    | '/api/profile'
    | '/api/assets/history'
    | '/api/assets/transfers'
    | '/api/auth/$'
    | '/api/ledger/analytics'
    | '/api/ledger/summary'
    | '/api/ocr/receipt'
    | '/api/receipts/$id'
    | '/api/assets/accounts/$id'
    | '/api/ledger/categories/$id'
    | '/api/ledger/transactions/$id'
    | '/api/ledger/transactions/duplicates'
    | '/api/planning/monthly-targets/$id'
    | '/api/planning/recurring-rules/$id'
    | '/api/planning/recurring-rules/run'
    | '/api/receipts/$id/image'
    | '/api/receipts/$id/retry'
    | '/api/assets/accounts/'
    | '/api/ledger/categories/'
    | '/api/ledger/transactions/'
    | '/api/planning/monthly-targets/'
    | '/api/planning/recurring-rules/'
    | '/api/assets/accounts/$id/adjustments'
    | '/api/assets/accounts/$id/entries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/signup'
    | '/api/health'
    | '/api/profile'
    | '/api/assets/history'
    | '/api/assets/transfers'
    | '/api/auth/$'
    | '/api/ledger/analytics'
    | '/api/ledger/summary'
    | '/api/ocr/receipt'
    | '/api/receipts/$id'
    | '/api/assets/accounts/$id'
    | '/api/ledger/categories/$id'
    | '/api/ledger/transactions/$id'
    | '/api/ledger/transactions/duplicates'
    | '/api/planning/monthly-targets/$id'
    | '/api/planning/recurring-rules/$id'
    | '/api/planning/recurring-rules/run'
    | '/api/receipts/$id/image'
    | '/api/receipts/$id/retry'
    | '/api/assets/accounts'
    | '/api/ledger/categories'
    | '/api/ledger/transactions'
    | '/api/planning/monthly-targets'
    | '/api/planning/recurring-rules'
    | '/api/assets/accounts/$id/adjustments'
    | '/api/assets/accounts/$id/entries'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/signup'
    | '/api/health'
    | '/api/profile'
    | '/api/assets/history'
    | '/api/assets/transfers'
    | '/api/auth/$'
    | '/api/ledger/analytics'
    | '/api/ledger/summary'
    | '/api/ocr/receipt'
    | '/api/receipts/$id'
    | '/api/assets/accounts/$id'
    | '/api/ledger/categories/$id'
    | '/api/ledger/transactions/$id'
    | '/api/ledger/transactions/duplicates'
    | '/api/planning/monthly-targets/$id'
    | '/api/planning/recurring-rules/$id'
    | '/api/planning/recurring-rules/run'
    | '/api/receipts/$id/image'
    | '/api/receipts/$id/retry'
    | '/api/assets/accounts/'
    | '/api/ledger/categories/'
    | '/api/ledger/transactions/'
    | '/api/planning/monthly-targets/'
    | '/api/planning/recurring-rules/'
    | '/api/assets/accounts/$id/adjustments'
    | '/api/assets/accounts/$id/entries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiAssetsHistoryRoute: typeof ApiAssetsHistoryRoute
  ApiAssetsTransfersRoute: typeof ApiAssetsTransfersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLedgerAnalyticsRoute: typeof ApiLedgerAnalyticsRoute
  ApiLedgerSummaryRoute: typeof ApiLedgerSummaryRoute
  ApiOcrReceiptRoute: typeof ApiOcrReceiptRoute
  ApiReceiptsIdRoute: typeof ApiReceiptsIdRouteWithChildren
  ApiAssetsAccountsIdRoute: typeof ApiAssetsAccountsIdRouteWithChildren
  ApiLedgerCategoriesIdRoute: typeof ApiLedgerCategoriesIdRoute
  ApiLedgerTransactionsIdRoute: typeof ApiLedgerTransactionsIdRoute
  ApiLedgerTransactionsDuplicatesRoute: typeof ApiLedgerTransactionsDuplicatesRoute
  ApiPlanningMonthlyTargetsIdRoute: typeof ApiPlanningMonthlyTargetsIdRoute
  ApiPlanningRecurringRulesIdRoute: typeof ApiPlanningRecurringRulesIdRoute
  ApiPlanningRecurringRulesRunRoute: typeof ApiPlanningRecurringRulesRunRoute
  ApiAssetsAccountsIndexRoute: typeof ApiAssetsAccountsIndexRoute
  ApiLedgerCategoriesIndexRoute: typeof ApiLedgerCategoriesIndexRoute
  ApiLedgerTransactionsIndexRoute: typeof ApiLedgerTransactionsIndexRoute
  ApiPlanningMonthlyTargetsIndexRoute: typeof ApiPlanningMonthlyTargetsIndexRoute
  ApiPlanningRecurringRulesIndexRoute: typeof ApiPlanningRecurringRulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/history': {
      id: '/api/assets/history'
      path: '/api/assets/history'
      fullPath: '/api/assets/history'
      preLoaderRoute: typeof ApiAssetsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/transfers': {
      id: '/api/assets/transfers'
      path: '/api/assets/transfers'
      fullPath: '/api/assets/transfers'
      preLoaderRoute: typeof ApiAssetsTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger/analytics': {
      id: '/api/ledger/analytics'
      path: '/api/ledger/analytics'
      fullPath: '/api/ledger/analytics'
      preLoaderRoute: typeof ApiLedgerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger/summary': {
      id: '/api/ledger/summary'
      path: '/api/ledger/summary'
      fullPath: '/api/ledger/summary'
      preLoaderRoute: typeof ApiLedgerSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocr/receipt': {
      id: '/api/ocr/receipt'
      path: '/api/ocr/receipt'
      fullPath: '/api/ocr/receipt'
      preLoaderRoute: typeof ApiOcrReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts/$id': {
      id: '/api/receipts/$id'
      path: '/api/receipts/$id'
      fullPath: '/api/receipts/$id'
      preLoaderRoute: typeof ApiReceiptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/accounts/': {
      id: '/api/assets/accounts/'
      path: '/api/assets/accounts'
      fullPath: '/api/assets/accounts/'
      preLoaderRoute: typeof ApiAssetsAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/accounts/$id': {
      id: '/api/assets/accounts/$id'
      path: '/api/assets/accounts/$id'
      fullPath: '/api/assets/accounts/$id'
      preLoaderRoute: typeof ApiAssetsAccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger/categories/': {
      id: '/api/ledger/categories/'
      path: '/api/ledger/categories'
      fullPath: '/api/ledger/categories/'
      preLoaderRoute: typeof ApiLedgerCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger/categories/$id': {
      id: '/api/ledger/categories/$id'
      path: '/api/ledger/categories/$id'
      fullPath: '/api/ledger/categories/$id'
      preLoaderRoute: typeof ApiLedgerCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger/transactions/': {
      id: '/api/ledger/transactions/'
      path: '/api/ledger/transactions'
      fullPath: '/api/ledger/transactions/'
      preLoaderRoute: typeof ApiLedgerTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger/transactions/$id': {
      id: '/api/ledger/transactions/$id'
      path: '/api/ledger/transactions/$id'
      fullPath: '/api/ledger/transactions/$id'
      preLoaderRoute: typeof ApiLedgerTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger/transactions/duplicates': {
      id: '/api/ledger/transactions/duplicates'
      path: '/api/ledger/transactions/duplicates'
      fullPath: '/api/ledger/transactions/duplicates'
      preLoaderRoute: typeof ApiLedgerTransactionsDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planning/monthly-targets/': {
      id: '/api/planning/monthly-targets/'
      path: '/api/planning/monthly-targets'
      fullPath: '/api/planning/monthly-targets/'
      preLoaderRoute: typeof ApiPlanningMonthlyTargetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planning/monthly-targets/$id': {
      id: '/api/planning/monthly-targets/$id'
      path: '/api/planning/monthly-targets/$id'
      fullPath: '/api/planning/monthly-targets/$id'
      preLoaderRoute: typeof ApiPlanningMonthlyTargetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planning/recurring-rules/': {
      id: '/api/planning/recurring-rules/'
      path: '/api/planning/recurring-rules'
      fullPath: '/api/planning/recurring-rules/'
      preLoaderRoute: typeof ApiPlanningRecurringRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planning/recurring-rules/$id': {
      id: '/api/planning/recurring-rules/$id'
      path: '/api/planning/recurring-rules/$id'
      fullPath: '/api/planning/recurring-rules/$id'
      preLoaderRoute: typeof ApiPlanningRecurringRulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planning/recurring-rules/run': {
      id: '/api/planning/recurring-rules/run'
      path: '/api/planning/recurring-rules/run'
      fullPath: '/api/planning/recurring-rules/run'
      preLoaderRoute: typeof ApiPlanningRecurringRulesRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts/$id/image': {
      id: '/api/receipts/$id/image'
      path: '/image'
      fullPath: '/api/receipts/$id/image'
      preLoaderRoute: typeof ApiReceiptsIdImageRouteImport
      parentRoute: typeof ApiReceiptsIdRoute
    }
    '/api/receipts/$id/retry': {
      id: '/api/receipts/$id/retry'
      path: '/retry'
      fullPath: '/api/receipts/$id/retry'
      preLoaderRoute: typeof ApiReceiptsIdRetryRouteImport
      parentRoute: typeof ApiReceiptsIdRoute
    }
    '/api/assets/accounts/$id/adjustments': {
      id: '/api/assets/accounts/$id/adjustments'
      path: '/adjustments'
      fullPath: '/api/assets/accounts/$id/adjustments'
      preLoaderRoute: typeof ApiAssetsAccountsIdAdjustmentsRouteImport
      parentRoute: typeof ApiAssetsAccountsIdRoute
    }
    '/api/assets/accounts/$id/entries': {
      id: '/api/assets/accounts/$id/entries'
      path: '/entries'
      fullPath: '/api/assets/accounts/$id/entries'
      preLoaderRoute: typeof ApiAssetsAccountsIdEntriesRouteImport
      parentRoute: typeof ApiAssetsAccountsIdRoute
    }
  }
}

interface ApiReceiptsIdRouteChildren {
  ApiReceiptsIdImageRoute: typeof ApiReceiptsIdImageRoute
  ApiReceiptsIdRetryRoute: typeof ApiReceiptsIdRetryRoute
}

const ApiReceiptsIdRouteChildren: ApiReceiptsIdRouteChildren = {
  ApiReceiptsIdImageRoute: ApiReceiptsIdImageRoute,
  ApiReceiptsIdRetryRoute: ApiReceiptsIdRetryRoute,
}

const ApiReceiptsIdRouteWithChildren = ApiReceiptsIdRoute._addFileChildren(
  ApiReceiptsIdRouteChildren,
)

interface ApiAssetsAccountsIdRouteChildren {
  ApiAssetsAccountsIdAdjustmentsRoute: typeof ApiAssetsAccountsIdAdjustmentsRoute
  ApiAssetsAccountsIdEntriesRoute: typeof ApiAssetsAccountsIdEntriesRoute
}

const ApiAssetsAccountsIdRouteChildren: ApiAssetsAccountsIdRouteChildren = {
  ApiAssetsAccountsIdAdjustmentsRoute: ApiAssetsAccountsIdAdjustmentsRoute,
  ApiAssetsAccountsIdEntriesRoute: ApiAssetsAccountsIdEntriesRoute,
}

const ApiAssetsAccountsIdRouteWithChildren =
  ApiAssetsAccountsIdRoute._addFileChildren(ApiAssetsAccountsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiAssetsHistoryRoute: ApiAssetsHistoryRoute,
  ApiAssetsTransfersRoute: ApiAssetsTransfersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLedgerAnalyticsRoute: ApiLedgerAnalyticsRoute,
  ApiLedgerSummaryRoute: ApiLedgerSummaryRoute,
  ApiOcrReceiptRoute: ApiOcrReceiptRoute,
  ApiReceiptsIdRoute: ApiReceiptsIdRouteWithChildren,
  ApiAssetsAccountsIdRoute: ApiAssetsAccountsIdRouteWithChildren,
  ApiLedgerCategoriesIdRoute: ApiLedgerCategoriesIdRoute,
  ApiLedgerTransactionsIdRoute: ApiLedgerTransactionsIdRoute,
  ApiLedgerTransactionsDuplicatesRoute: ApiLedgerTransactionsDuplicatesRoute,
  ApiPlanningMonthlyTargetsIdRoute: ApiPlanningMonthlyTargetsIdRoute,
  ApiPlanningRecurringRulesIdRoute: ApiPlanningRecurringRulesIdRoute,
  ApiPlanningRecurringRulesRunRoute: ApiPlanningRecurringRulesRunRoute,
  ApiAssetsAccountsIndexRoute: ApiAssetsAccountsIndexRoute,
  ApiLedgerCategoriesIndexRoute: ApiLedgerCategoriesIndexRoute,
  ApiLedgerTransactionsIndexRoute: ApiLedgerTransactionsIndexRoute,
  ApiPlanningMonthlyTargetsIndexRoute: ApiPlanningMonthlyTargetsIndexRoute,
  ApiPlanningRecurringRulesIndexRoute: ApiPlanningRecurringRulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
